config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  root 'store#index'

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)

  post '/products/:product_id/comments' => 'comments#create', as: 'product_comments'
  get '/catalog' => 'products#index', as: 'products'
  # get '/c/:category_id/p/:id' => 'products#show', as: 'category_product'
  # get '/c/:id' => 'categories#show', as: 'category'

  resources :visitors, only: [:create]
  resources :articles, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :users, only: [:show]
  resource :shopping_cart, only: [:show, :destroy]
  resource :shopping_cart_items, only: [:create, :destroy, :update]
  resources :contacts, only: [:new, :create] do
    post 'callback', on: :collection, as: :callback
  end

  # get 'o-nas' => 'pages#about', as: 'about'
  # get 'oplata-i-dostavka' => 'pages#pay_and_delivery', as: 'pay_and_delivery'
  get ':id' => 'pages#show', as: :page

  get "c/:id" => 'categories#show', :as => :category_short
  get "c/:category/:id" => 'categories#show', :as => :category_long

  get '/c/:category_id/p/:id' => 'products#show', as: 'category_product_short'
  get '/c/:category/:category_id/p/:id' => 'products#show', as: 'category_product_long'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :read, Order, user: user
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  
  paginates_per 10

  friendly_id :title, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :product
  validates :file, presence: true

  mount_uploader :file, DocumentUploader

  scope :uniq_by_product, -> { select('DISTINCT ON (product_id) *') }
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  extend FriendlyId
  has_many :products, dependent: :destroy

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  has_many :products
  
  has_ancestry :orphan_strategy => :rootify, :cache_depth => true

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  has_many :comment_replies
  
  validates :user_name, :body, presence: true

  default_scope { order(:updated_at) }
end

app/models/comment_reply.rb
class CommentReply < ActiveRecord::Base
	belongs_to :comment
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string
  attr_accessor :phone, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :shopping_cart_items, dependent: :destroy
  belongs_to :user
  validates :name, :last_name, :adress, :phone, presence: true
  validates :email, presence: true, if: :online_payment_needed

  attr_accessor :online_payment

  def add_line_items_from_cart(cart)
    cart.shopping_cart_items.each do |item|
      item.owner_id = nil
      item.owner_type = nil
      shopping_cart_items << item
    end
  end

  def add_total_price(cart)
    self.total_price = cart.total
  end

  def online_payment_needed
    online_payment == 'true'
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  belongs_to :category

  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
  mount_uploaders :gallery, GalleryUploader

  scope :all_except, ->(product) { where.not(id: product.id) }
  scope :similar, ->(product){
   joins(:tags).where('tags.name = ?', "#{product.tags.first.name}" ) if product.tags.present?
  }
  scope :novinki, -> { includes(:tags).where(tags: {name: 'novinki'}).references(:tags) }
  scope :popular, -> { includes(:tags).where(tags: {name: 'popular'}).references(:tags) }

  validates :category, :tags, :title, :description, :image, :price, presence: true

  friendly_id :title, use: :slugged

  paginates_per 15

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def remove(object, quantity = 1)
    cart_item = item_for(object)
    return unless cart_item

    cart_item.delete
  end

  def add(object, price, quantity = 1, cumulative = true)
    cart_item = item_for(object)

    if cart_item
      cumulative = cumulative == true ? cart_item.quantity : 0
      cart_item.quantity = (cumulative + quantity)
      cart_item.save
      cart_item
    else
      shape_size = object.shape_sizes.present? ? 1.5 : nil
      shopping_cart_items.create(item: object, price: price, quantity: quantity, shape_size: shape_size)
    end
  end

  def total
    subtotal
  end

  def self.remove_old_records
    old_record = ShoppingCart.where('created_at < ?', 7.days.ago)
    delete(old_record)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  layout "orders"
  before_action :set_cart
  before_action :find_categories

  def show
    @shape_size_present = @shopping_cart.shopping_cart_items.any? do |shopping_cart_item|
      shopping_cart_item.item.shape_sizes.any?(&:present?)
    end
  end

  def destroy
    @shopping_cart.clear
    redirect_to root_path
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/store_helper.rb
module StoreHelper
  def product_feature features

    return if features.nil? or features.empty?

    message = case features
      when "sale"
        "Акция"
      when "new"
        "Новинка"
      else "gift"
        "Бесплатная доставка"
    end

    html = <<-HTML
    <div class="ribbon #{features}" >
        <div class="theribbon" style="margin-top: 0;">#{message}</div>
        <div class="ribbon-background"></div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shopping_carts/show.html.erb
<div class="shopping-cart">
  <h1>Корзина</h1>

  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Товар</label>
    <label class="product-price">Цена</label>
    <% if @shape_size_present %>
      <label class="product-quantity">Нагрузка</label>
    <% end %>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Итого</label>
  </div>

  <% @shopping_cart.shopping_cart_items.each do |shopping_cart_item| %>
    <div class="product2">
      <div class="product-image">
        <%= link_to category_product_path(shopping_cart_item.item) do %>
            <%= image_tag shopping_cart_item.item.image.preview, class:"img-responsive" %>
        <% end %>
      </div>
      <div class="product-details">
        <div class="product-title">
          <%= link_to shopping_cart_item.item.title, category_product_path(shopping_cart_item.item) %>
        </div>
      </div>
      <div class="product-price">
        <%= shopping_cart_item.item.price %>
      </div>

      <% if @shape_size_present %>
        <div class="product-weight">
          Нагрузка
        </div>
      <% end %>

      <% if @shape_size_present %>
        <div class="product-quantity">
          <% if shopping_cart_item.item.shape_sizes.any?(&:present?) %>
            <%= form_for shopping_cart_item, :url => shopping_cart_items_path(:item_id => shopping_cart_item.id), :html => { :class => 'form-inline'} do |f| %>
              <%= f.select(:shape_size, shopping_cart_item.item.shape_sizes.reject(&:blank?).map { |s| [{ '1.5' => 'до 80 кг', '2.0' => 'до 120 кг', '2.5' => 'до 150 кг' }.fetch(s), s] }, {}, {:onchange => 'this.form.submit()'}) %>
            <% end %>
          <% else %>
            -
          <% end %>
        </div>
      <% end %>
      <div class="product-removal">
        <%= link_to shopping_cart_items_path(:product_id => shopping_cart_item.item.id), method: :delete do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
      <div class="product-line-price">
        <%= number_to_currency shopping_cart_item.subtotal %>
      </div>
    </div>
  <% end %>

  <div class="totals">
    <div class="totals-item">
      <label>Итого</label>
      <div class="totals-value" id="cart-subtotal">
        <%= number_to_currency @shopping_cart.total %>
      </div>
    </div>
  </div>

  <%= button_to new_order_path, class: "checkout", method: :get do %>
    Оформить заказ
  <% end %>
</div>