config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  root 'store#index'

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)

  post '/products/:product_id/comments' => 'comments#create', as: 'product_comments'
  get '/catalog' => 'products#index', as: 'products'
  # get '/c/:category_id/p/:id' => 'products#show', as: 'category_product'
  # get '/c/:id' => 'categories#show', as: 'category'

  resources :visitors, only: [:create]
  resources :articles, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :users, only: [:show]
  resource :shopping_cart, only: [:show, :destroy]
  resource :shopping_cart_items, only: [:create, :destroy, :update]
  resources :contacts, only: [:new, :create] do
    post 'callback', on: :collection, as: :callback
  end

  # get 'o-nas' => 'pages#about', as: 'about'
  # get 'oplata-i-dostavka' => 'pages#pay_and_delivery', as: 'pay_and_delivery'
  get ':id' => 'pages#show', as: :page

  get "c/:id" => 'categories#show', :as => :category_short
  get "c/:category/:id" => 'categories#show', :as => :category_long

  get '/c/:category_id/p/:id' => 'products#show', as: 'category_product_short'
  get '/c/:category/:category_id/p/:id' => 'products#show', as: 'category_product_long'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :read, Order, user: user
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  
  paginates_per 10

  friendly_id :title, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :product
  validates :file, presence: true

  mount_uploader :file, DocumentUploader

  scope :uniq_by_product, -> { select('DISTINCT ON (product_id) *') }
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  extend FriendlyId
  has_many :products, dependent: :destroy

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  has_many :products
  
  has_ancestry :orphan_strategy => :rootify, :cache_depth => true

  friendly_id :name, use: :slugged

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  has_many :comment_replies
  
  validates :user_name, :body, presence: true

  default_scope { order(:updated_at) }
end

app/models/comment_reply.rb
class CommentReply < ActiveRecord::Base
	belongs_to :comment
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string
  attr_accessor :phone, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :shopping_cart_items, dependent: :destroy
  belongs_to :user
  validates :name, :last_name, :adress, :phone, presence: true
  validates :email, presence: true, if: :online_payment_needed

  attr_accessor :online_payment

  def add_line_items_from_cart(cart)
    cart.shopping_cart_items.each do |item|
      item.owner_id = nil
      item.owner_type = nil
      shopping_cart_items << item
    end
  end

  def add_total_price(cart)
    self.total_price = cart.total
  end

  def online_payment_needed
    online_payment == 'true'
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  belongs_to :category

  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
  mount_uploaders :gallery, GalleryUploader

  scope :all_except, ->(product) { where.not(id: product.id) }
  scope :similar, ->(product){
   joins(:tags).where('tags.name = ?', "#{product.tags.first.name}" ) if product.tags.present?
  }
  scope :novinki, -> { includes(:tags).where(tags: {name: 'novinki'}).references(:tags) }
  scope :popular, -> { includes(:tags).where(tags: {name: 'popular'}).references(:tags) }

  validates :category, :tags, :title, :description, :image, :price, presence: true

  friendly_id :title, use: :slugged

  paginates_per 15

  def normalize_friendly_id(text)
    text.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def remove(object, quantity = 1)
    cart_item = item_for(object)
    return unless cart_item

    cart_item.delete
  end

  def add(object, price, quantity = 1, cumulative = true)
    cart_item = item_for(object)

    if cart_item
      cumulative = cumulative == true ? cart_item.quantity : 0
      cart_item.quantity = (cumulative + quantity)
      cart_item.save
      cart_item
    else
      shape_size = object.shape_sizes.present? ? 1.5 : nil
      shopping_cart_items.create(item: object, price: price, quantity: quantity, shape_size: shape_size)
    end
  end

  def total
    subtotal
  end

  def self.remove_old_records
    old_record = ShoppingCart.where('created_at < ?', 7.days.ago)
    delete(old_record)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/store_helper.rb
module StoreHelper
  def product_feature features

    return if features.nil? or features.empty?

    message = case features
      when "sale"
        "Акция"
      when "new"
        "Новинка"
      else "gift"
        "Бесплатная доставка"
    end

    html = <<-HTML
    <div class="ribbon #{features}" >
        <div class="theribbon" style="margin-top: 0;">#{message}</div>
        <div class="ribbon-background"></div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_breadcrumbs.html.erb
<% content_for :breadcrumbs do %>
  <div id="heading-breadcrumbs" class="col-md-12">
    <div class="container">
        <div class="row">
          <ul class="breadcrumb">
            <li><%= link_to "Главная", root_path %></li>
             <li><%= @product.title %></li>
          </ul>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/_cart.html.erb
<%= link_to shopping_cart_path, class: "btn btn-primary navbar-btn" do %>
  <i class="fa fa-shopping-cart"></i>
  <% if @shopping_cart and !@shopping_cart.empty? %>
    <span class="hidden-sm"><%=number_to_currency(@shopping_cart.total) %></span>
  <% else %>
    <span class="hidden-sm">Корзина пуста</span>
  <% end %>
<% end %>

app/views/layouts/_copyright.html.erb
<div id="copyright">
    <div class="container">
        <div class="col-md-6">
            <p class="pull-left">© 2015 - 2019 Ладас.укр</p>
        </div>
        <div class="col-md-6">
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <h4>Информация</h4>
                <ul>
                    <li>
                        <%= link_to "О компании", page_path("o-nas") %>
                    </li>
                    <li>
                        <%= link_to "Оплата и доставка", page_path("oplata-i-dostavka") %>
                    </li>
                    <li>
                        <%= link_to "Новости", articles_path %>
                    </li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4>Служба поддержки</h4>
                <ul>
                    <li>
                        <%= link_to "Связаться с нами", new_contact_path %>
                    </li>
                    <li>
                        <%= link_to "Возврат товара", page_path("oplata-i-dostavka") %>
                    </li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4>Номера телефонов</h4>
                <ul>
                    <li><a href="#"> +3 8(096) 543 38 24</a></li>
                </ul>
            </div>
            <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <h4>Мы в соцсетях</h4>
                <p class="social">
                            <a href="https://www.facebook.com/groups/ladas.ukr" rel="nofollow" class="facebook external" data-animate-hover="shake" style="opacity: 1;"><i class="fa fa-facebook"></i></a>
                            <a href="https://plus.google.com/+ЛадасУкраина" rel="nofollow" class="gplus external" data-animate-hover="shake" style="opacity: 1;"><i class="fa fa-google-plus"></i></a>
                </p>

            </div>
            <!-- /.col-md-3 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand home" href="/">
                <%= image_tag "logo.png", class: "hidden-xs" %>
                <%= image_tag "logo-small.png", class: "visible-xs" %>
            </a>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-align-justify"></i>
                </button>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
                <%= link_to shopping_cart_path, class: "btn btn-default navbar-toggle" do %>
                  <i class="fa fa-shopping-cart"></i>
                  <% if @shopping_cart and !@shopping_cart.empty? %>
                    <span class="hidden-xs"><%=number_to_currency(@shopping_cart.total) %></span>
                  <% else %>
                    <span class="hidden-xs">Корзина пуста</span>
                  <% end %>
                <% end %>
            </div>
        </div>
        <!--/.navbar-header -->
        <div class="navbar-collapse collapse" id="navigation">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="/">Главная</a>
                </li>
                <li>
                    <%= link_to "О нас", page_path("o-nas") %>
                </li>
                <li>
                    <%= link_to "Каталог", products_path %>
                </li>
                <li>
                    <%= link_to "Оплата и доставка", page_path("oplata-i-dostavka") %>
                </li>
                <li>
                    <%= link_to "Сотрудничество", page_path("sotrudnichestvo") %>
                </li>
                <li>
                    <%= link_to "Контакты", new_contact_path %>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
        <div class="navbar-buttons">
            <div class="navbar-collapse collapse right" id="basket-overview">
                <%= render 'layouts/cart' %>
            </div>
            <!--/.nav-collapse -->
            <div class="navbar-collapse collapse right" id="search-not-mobile">
                <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
        <div class="collapse clearfix" id="search">
            <%= search_form_for Product.ransack(params[:q]), html: {class: "navbar-form", role: "search" } do |f| %>
                <div class="input-group">
                  <%= f.search_field :title_cont, placeholder: "Поиск", class: "form-control" %>
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                  </span>
                </div>
            <% end %>
        </div>
        <!--/.nav-collapse -->
    </div>
    <!-- /.container -->
</div>

app/views/layouts/_sidebar.html.erb
<div class="panel panel-default sidebar-menu">
    <div class="panel-heading">
        <h3 class="panel-title">Категории</h3>
    </div>
    <div class="panel-body">
      <%= arranged_tree_as_list(@categories, {:sort_by => [:position], 
          :ul_class_top => ["nav", "nav-pills", "nav-stacked", "category-menu", "menu_active"]}) do |category| %>
        <%= link_to category.name, category_path(category) %>
      <% end %> 
    </div>
</div>

app/views/layouts/_top.html.erb
<div id="top">
    <div class="container">
      <div class="col-md-6 offer" style="margin-bottom: 0px;">
          <a href="tel:+380965433824" onclick="gtag_report_conversion();" style="font-size: 18px;"><i class="fa fa-phone"></i> +3 8(096) 543 38 24</a>&nbsp
            <a href="#" data-toggle="modal" data-target="#callback-modal" class="btn btn-success btn-sm"><i class="fa fa-phone">
                </i>Заказать обратный звонок
            </a>
        </div>
        <div class="col-md-6">
            <ul class="menu">
                <li><% if user_signed_in? %>
                        <%= link_to "Выход", destroy_user_session_path, method: :delete %>
                    <% else %>
                        <a href="#" data-toggle="modal" data-target="#login-modal">Войти</a>
                    <% end %>
                </li>
                <li>
                    <% if user_signed_in? %>
                        <%= link_to root_path do %>
                            <i class="fa fa-user"></i>
                            <%= link_to current_user.email, orders_path %>
                        <% end %>
                    <% else %>
                        <%= link_to 'Регистрация', new_user_session_path %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "Контакты", new_contact_path %>
                </li>
            </ul>
        </div>
    </div>
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Войти</h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:user, :url => user_session_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.label :email, "Ел. почта" %>
                            <%= f.email_field :email, :autofocus => true, class: 'form-control' %>
                        </div>
                        <div class="form-group">
                            <%= f.label :password, "Пароль" %>
                            <%= f.password_field :password, class: 'form-control' %>
                        </div>
                        <%= f.submit 'Войти', :class => 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="callback-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Обратный звонок</h4>
                </div>
                <div class="modal-body">
                    <%= form_for(:contact, url: callback_contacts_path, :html => { :role => 'form'}) do |f| %>
                        <div class="form-group">
                            <%= f.label :name, "Ваше имя" %>
                            <%= f.text_field :name, :autofocus => true, class: 'form-control', required: true%>
                        </div>
                        <div class="form-group">
                            <%= f.label :phone, "Телефон" %>
                            <%= f.text_field :phone, class: 'form-control' %>
                        </div>
                        <%= f.submit 'Заказать звонок', :class => 'btn btn-primary', :onclick => "gtag_report_conversion();"  %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Ads: 919364254 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-919364254"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'AW-919364254');
    </script>
    <!-- Event snippet for Звонок-1 conversion page
    In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
    <script>
    function gtag_report_conversion(url) {
      var callback = function () {
        if (typeof(url) != 'undefined') {
          window.location = url;
        }
      };
      gtag('event', 'conversion', {
          'send_to': 'AW-919364254/SNelCJqexdoBEJ7FsbYD',
          'event_callback': callback
      });
      return false;
    }
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ладас.укр | Шведские стенки Ладас" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ладас.укр - официальный сайт, шведские стенки Ладас, цены от производителя" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700italic,700,500italic,500,400italic,300,300italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
  </head>
  <body>
      <%= render 'layouts/top' %>
      <%= render 'layouts/navbar' %>
      <div id="all">
        <div id="content">
            <div class="container">
                <%= yield(:breadcrumbs) %>
                <div class="col-md-3">
                    <%= yield(:user_menu) %>
                    <%= render 'layouts/sidebar' %>
                </div>
                <div class="col-md-9">
                    <%= render 'layouts/messages' %>
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= render 'layouts/footer' %>
        <%= render 'layouts/copyright' %>
      </div>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
  </body>
</html>

app/views/layouts/orders.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Ads: 919364254 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-919364254"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'AW-919364254');
    </script>

    <!-- Event snippet for Покупка-7 conversion page -->
    <script>
      function gtag_report_conversion(url) {
        var callback = function () {
          if (typeof(url) != 'undefined') {
            window.location = url;
          }
        };
        gtag('event', 'conversion', {
            'send_to': 'AW-919364254/SNelCJqexdoBEJ7FsbYD',
            'event_callback': callback
        });
        return false;
      }
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ладас.укр | Шведские стенки Ладас" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ладас.укр - официальный сайт, шведские стенки Ладас, цены от производителя" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700italic,700,500italic,500,400italic,300,300italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
</head>


  <body>

      <%= render 'layouts/top' %>
      <%= render 'layouts/navbar' %>
      <div id="all">
        <div id="content">
            <div class="container">
                <%= yield(:breadcrumbs) %>
                <div class="col-md-3">
                    <%= yield(:user_menu) %>
                    <div class="hidden-xs">
                      <%= render 'layouts/sidebar' %>
                    </div>
                </div>
                <div class="col-md-9">
                    <%= render 'layouts/messages' %>
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= render 'layouts/footer' %>
        <%= render 'layouts/copyright' %>
      </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>